常用的库

In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.optim import Adam
from torchvision import transforms,datasets

常用的数据生成方式

In [80]:
# 生成一个 2x3 的张量，元素值在 [0, 1) 之间均匀分布
x = torch.rand(2, 3)
# 示例输出：
# tensor([[0.1234, 0.5678, 0.9101],
#         [0.2345, 0.6789, 0.0123]])
print(x)

tensor([[0.2573, 0.9508, 0.9287],
        [0.2140, 0.5410, 0.7977]])


In [ ]:
# 生成一个 2x3 的张量，元素服从标准正态分布 N(0, 1)
x = torch.randn(2, 3,device='cuda')
# 示例输出：
# tensor([[ 0.1234, -0.5678,  1.2345],
#         [-0.9876,  0.4321, -0.1111]])

In [81]:
# 生成一个 2x3 的张量，元素为 [0, 10) 之间的随机整数
x = torch.randint(0, 10, (2, 3))
# 示例输出：
# tensor([[3, 7, 2],
#         [8, 1, 9]])

In [88]:
# 生成一个长度为 5 的随机排列，范围为 [0, 5)
x = torch.randperm(5)
# 示例输出：
# tensor([2, 0, 4, 1, 3])
x

tensor([4, 1, 2, 3, 0])

In [89]:
# 生成一个 2x3 的全 0 张量
x = torch.zeros(2, 3)
# 示例输出：
# tensor([[0., 0., 0.],
#         [0., 0., 0.]])

In [91]:
# 生成一个 2x3 的全 1 张量
x = torch.ones(2, 3)
# 示例输出：
# tensor([[1., 1., 1.],
#         [1., 1., 1.]])

In [92]:
# 生成一个 2x3 的张量，元素值全为 5
x = torch.full((2, 3), 5)
# 示例输出：
# tensor([[5, 5, 5],
#         [5, 5, 5]])

In [94]:
# 生成一个 3x3 的单位矩阵
x = torch.eye(3)
# 示例输出：
# tensor([[1., 0., 0.],
#         [0., 1., 0.],
#         [0., 0., 1.]])
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [95]:
# 生成从 0 开始，到 10 结束（不包括 10），步长为 2 的数列
x = torch.arange(0, 10, 2)
# 示例输出：
# tensor([0, 2, 4, 6, 8])

In [96]:
# 生成从 0 到 1 的 5 个等间隔数
x = torch.linspace(0, 1, 5)
# 示例输出：
# tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [99]:
# 生成从 10^0 到 10^1 的 5 个对数间隔数
x = torch.logspace(0, 1, 5)
# 示例输出：
# tensor([ 1.0000,  1.7783,  3.1623,  5.6234, 10.0000])
x

tensor([ 1.0000,  1.7783,  3.1623,  5.6234, 10.0000])

几个重要的方法（主要是深拷贝）

In [100]:
# 创建一个张量
x = torch.tensor([1, 2, 3])
# 复制 x
y = x.clone()
if id(x) != id(y):
    print("True")
else:
    print("False")
# 示例输出：
# tensor([1, 2, 3])

True


In [ ]:
# 创建一个张量
x = torch.tensor([[1, 2], [3, 4]])
# 生成与 x 形状相同的全 0 张量
y = torch.zeros_like(x)
# 示例输出：
# tensor([[0, 0],
#         [0, 0]])

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 创建一个空张量
z = torch.empty_like(x[0, :])

# 使用 copy_ 复制数据
z.copy_(x[0, :])  # 深拷贝